In [1]:
import pandas as pd
  
  
df = pd.read_json("transaction-data-adhoc-analysis.json")
df.head()

,address,birthdate,mail,name,sex,username,transaction_items,transaction_value,transaction_date
0,USNS Wagner\nFPO AE 00917,1926/03/11,watsonbrenda@gmail.com,Jennifer Campbell,F,veronicawells,"Exotic Extras,Beef Chicharon,(x4)",5196,2022/01/12
1,USCGC Benson\nFPO AP 48794,2016/07/08,moorelisa@gmail.com,Melissa Kim,F,cgilbert,"Exotic Extras,Beef Chicharon,(x3);HealthyKid 3...",12056,2022/01/12
2,USCGC Benson\nFPO AP 48794,2016/07/08,moorelisa@gmail.com,Melissa Kim,F,cgilbert,"HealthyKid 3+,Gummy Vitamins,(x3);HealthyKid 3...",5500,2022/01/08
3,USCGC Benson\nFPO AP 48794,2016/07/08,moorelisa@gmail.com,Melissa Kim,F,cgilbert,"HealthyKid 3+,Yummy Vegetables,(x1)",500,2022/01/10
4,"33911 Hansen Loaf\nWest Sandra, ND 54188",1949/09/27,michael78@yahoo.com,Kristen Cooper,F,qhernandez,"Candy City,Orange Beans,(x3);Candy City,Gummy ...",2697,2022/01/24

In [2]:
df.duplicated(['name','username'],keep='first')

0        False
1        False
2         True
3         True
4        False
         ...
83031     True
83032     True
83033     True
83034     True
83035     True
Length: 83036, dtype: bool

In [3]:
print(df[df.duplicated('name')])

                                                 address   birthdate  \
2                             USCGC Benson\nFPO AP 48794  2016/07/08
3                             USCGC Benson\nFPO AP 48794  2016/07/08
8      63261 Brewer Drive Apt. 704\nLake Alicia, NJ 0...  1956/08/27
9      63261 Brewer Drive Apt. 704\nLake Alicia, NJ 0...  1956/08/27
11              2049 Schneider Walk\nScottfurt, DC 18004  1993/10/21
...                                                  ...         ...
83031      96081 Harrison Brooks\nJenniferbury, MA 02124  2019/10/26
83032  428 Kristopher Curve Apt. 206\nMcculloughville...  1913/11/04
83033  428 Kristopher Curve Apt. 206\nMcculloughville...  1913/11/04
83034  428 Kristopher Curve Apt. 206\nMcculloughville...  1913/11/04
83035                   PSC 1089, Box 3720\nAPO AE 08973  2012/04/30

                            mail               name sex    username  \
2            moorelisa@gmail.com        Melissa Kim   F    cgilbert
3            moorelisa@gmail.com        Melissa Kim   F    cgilbert
8           racheldiaz@gmail.com  Jennifer Figueroa   F   hoodbrett
9           racheldiaz@gmail.com  Jennifer Figueroa   F   hoodbrett
11           codydavis@gmail.com       Steven Woods   M  amandahill
...                          ...                ...  ..         ...
83031    christina55@hotmail.com         Tammy Byrd   F  kmcconnell
83032  melvinschmidt@hotmail.com    Donald Andersen   M       llowe
83033  melvinschmidt@hotmail.com    Donald Andersen   M       llowe
83034  melvinschmidt@hotmail.com    Donald Andersen   M       llowe
83035         xjones@hotmail.com  Stephanie Russell   F   cmcdowell

                                       transaction_items  transaction_value  \
2      HealthyKid 3+,Gummy Vitamins,(x3);HealthyKid 3...               5500
3                    HealthyKid 3+,Yummy Vegetables,(x1)                500
8                            Candy City,Gummy Worms,(x1)                150
9      HealthyKid 3+,Yummy Vegetables,(x1);Exotic Ext...              10196
11                     HealthyKid 3+,Gummy Vitamins,(x2)               3000
...                                                  ...                ...
83031  Exotic Extras,Kimchi and Seaweed,(x2);HealthyK...               3588
83032  HealthyKid 3+,Yummy Vegetables,(x1);Exotic Ext...               2095
83033  Candy City,Orange Beans,(x4);Candy City,Gummy ...               3396
83034  HealthyKid 3+,Nutrional Milk,(x2);Candy City,G...               4280
83035  HealthyKid 3+,Nutrional Milk,(x1);Candy City,G...               2639

      transaction_date
2           2022/01/08
3           2022/01/10
8           2022/01/11
9           2022/01/19
11          2022/01/01
...                ...
83031       2022/06/05
83032       2022/06/12
83033       2022/06/15
83034       2022/06/09
83035       2022/06/03

[74549 rows x 9 columns]

In [4]:
print((~df.duplicated()).sum())

83036

In [5]:
print(df.drop_duplicates())

                                                 address   birthdate  \
0                              USNS Wagner\nFPO AE 00917  1926/03/11
1                             USCGC Benson\nFPO AP 48794  2016/07/08
2                             USCGC Benson\nFPO AP 48794  2016/07/08
3                             USCGC Benson\nFPO AP 48794  2016/07/08
4               33911 Hansen Loaf\nWest Sandra, ND 54188  1949/09/27
...                                                  ...         ...
83031      96081 Harrison Brooks\nJenniferbury, MA 02124  2019/10/26
83032  428 Kristopher Curve Apt. 206\nMcculloughville...  1913/11/04
83033  428 Kristopher Curve Apt. 206\nMcculloughville...  1913/11/04
83034  428 Kristopher Curve Apt. 206\nMcculloughville...  1913/11/04
83035                   PSC 1089, Box 3720\nAPO AE 08973  2012/04/30

                            mail               name sex       username  \
0         watsonbrenda@gmail.com  Jennifer Campbell   F  veronicawells
1            moorelisa@gmail.com        Melissa Kim   F       cgilbert
2            moorelisa@gmail.com        Melissa Kim   F       cgilbert
3            moorelisa@gmail.com        Melissa Kim   F       cgilbert
4            michael78@yahoo.com     Kristen Cooper   F     qhernandez
...                          ...                ...  ..            ...
83031    christina55@hotmail.com         Tammy Byrd   F     kmcconnell
83032  melvinschmidt@hotmail.com    Donald Andersen   M          llowe
83033  melvinschmidt@hotmail.com    Donald Andersen   M          llowe
83034  melvinschmidt@hotmail.com    Donald Andersen   M          llowe
83035         xjones@hotmail.com  Stephanie Russell   F      cmcdowell

                                       transaction_items  transaction_value  \
0                      Exotic Extras,Beef Chicharon,(x4)               5196
1      Exotic Extras,Beef Chicharon,(x3);HealthyKid 3...              12056
2      HealthyKid 3+,Gummy Vitamins,(x3);HealthyKid 3...               5500
3                    HealthyKid 3+,Yummy Vegetables,(x1)                500
4      Candy City,Orange Beans,(x3);Candy City,Gummy ...               2697
...                                                  ...                ...
83031  Exotic Extras,Kimchi and Seaweed,(x2);HealthyK...               3588
83032  HealthyKid 3+,Yummy Vegetables,(x1);Exotic Ext...               2095
83033  Candy City,Orange Beans,(x4);Candy City,Gummy ...               3396
83034  HealthyKid 3+,Nutrional Milk,(x2);Candy City,G...               4280
83035  HealthyKid 3+,Nutrional Milk,(x1);Candy City,G...               2639

      transaction_date
0           2022/01/12
1           2022/01/12
2           2022/01/08
3           2022/01/10
4           2022/01/24
...                ...
83031       2022/06/05
83032       2022/06/12
83033       2022/06/15
83034       2022/06/09
83035       2022/06/03

[83036 rows x 9 columns]

In [6]:
print(df[df.duplicated('transaction_date')])

                                                 address   birthdate  \
1                             USCGC Benson\nFPO AP 48794  2016/07/08
7      63261 Brewer Drive Apt. 704\nLake Alicia, NJ 0...  1956/08/27
8      63261 Brewer Drive Apt. 704\nLake Alicia, NJ 0...  1956/08/27
12          222 Harris Summit\nNew Jenniferton, AL 51310  1930/04/29
15     1300 Williams Harbor Suite 673\nCruzfort, SC 8...  2004/01/27
...                                                  ...         ...
83031      96081 Harrison Brooks\nJenniferbury, MA 02124  2019/10/26
83032  428 Kristopher Curve Apt. 206\nMcculloughville...  1913/11/04
83033  428 Kristopher Curve Apt. 206\nMcculloughville...  1913/11/04
83034  428 Kristopher Curve Apt. 206\nMcculloughville...  1913/11/04
83035                   PSC 1089, Box 3720\nAPO AE 08973  2012/04/30

                            mail               name sex       username  \
1            moorelisa@gmail.com        Melissa Kim   F       cgilbert
7           racheldiaz@gmail.com  Jennifer Figueroa   F      hoodbrett
8           racheldiaz@gmail.com  Jennifer Figueroa   F      hoodbrett
12              zlin@hotmail.com    Benjamin Wilson   M        david85
15       johnsongerald@yahoo.com      Rhonda Madden   F  frazierjanice
...                          ...                ...  ..            ...
83031    christina55@hotmail.com         Tammy Byrd   F     kmcconnell
83032  melvinschmidt@hotmail.com    Donald Andersen   M          llowe
83033  melvinschmidt@hotmail.com    Donald Andersen   M          llowe
83034  melvinschmidt@hotmail.com    Donald Andersen   M          llowe
83035         xjones@hotmail.com  Stephanie Russell   F      cmcdowell

                                       transaction_items  transaction_value  \
1      Exotic Extras,Beef Chicharon,(x3);HealthyKid 3...              12056
7      HealthyKid 3+,Gummy Vitamins,(x2);HealthyKid 3...               6980
8                            Candy City,Gummy Worms,(x1)                150
12     Candy City,Gummy Worms,(x4);Exotic Extras,Beef...               3596
15     HealthyKid 3+,Gummy Vitamins,(x4);Candy City,O...               7697
...                                                  ...                ...
83031  Exotic Extras,Kimchi and Seaweed,(x2);HealthyK...               3588
83032  HealthyKid 3+,Yummy Vegetables,(x1);Exotic Ext...               2095
83033  Candy City,Orange Beans,(x4);Candy City,Gummy ...               3396
83034  HealthyKid 3+,Nutrional Milk,(x2);Candy City,G...               4280
83035  HealthyKid 3+,Nutrional Milk,(x1);Candy City,G...               2639

      transaction_date
1           2022/01/12
7           2022/01/08
8           2022/01/11
12          2022/01/24
15          2022/01/08
...                ...
83031       2022/06/05
83032       2022/06/12
83033       2022/06/15
83034       2022/06/09
83035       2022/06/03

[82855 rows x 9 columns]